# 写需要强开scx的游戏
[[hmbird_config]]
packages = [
    "com.miHoYo.Yuanshen",
    "com.miHoYo.GenshinImpact",
    "com.miHoYo.ys.bilibili",
    "com.miHoYo.yuanshencb",
    "com.miHoYo.hkrpg",
    "com.miHoYo.hkrpg.bilibili",
    "com.HoYoverse.hkrpgoversea",
    "com.miHoYo.hkrpgcb",
    "com.miHoYo.Nap",
    "com.tencent.KiHan",
    "com.ChillyRoom.DungeonShooter",
]

[hmbird_config.node_value]
"cluster_separate" = 0
"cpu7_tl" = 70
"cpu_cluster_masks" = 3145728
"cpuctrl_high" = 55
"cpuctrl_low" = 40
"highres_tick_ctrl_dbg" = 0
"hmbird_preempt_policy" = 0
"hmbirdcore_debug" = 0
"iso_free_rescue" = 0
"isoctrl_high_ratio" = 75
"isoctrl_low_ratio" = 60
"isolate_ctrl" = 0
"misfit_ds" = 90
"parctrl_high_ratio" = 55
"parctrl_high_ratio_l" = 65
"parctrl_low_ratio" = 40
"parctrl_low_ratio_l" = 50
"partial_ctrl" = 1
"save_gov" = 0
"scx_shadow_tick_enable" = 1
"slim_for_app" = 0
"slim_stats" = 0
"watchdog_enable" = 0


[[hmbird_config]]
packages = [
    "com.hypergryph.arknights",
    "com.tencent.tmgp.pubgmhd",
    "com.tencent.tmgp.sgame",
]

[hmbird_config.node_value]
"cluster_separate"        = 0
"cpu7_tl"                 = 70
"cpu_cluster_masks"       = 524288160
"cpuctrl_high"            = 55
"cpuctrl_low"             = 40
"highres_tick_ctrl_dbg"   = 0
"hmbird_preempt_policy"   = 0
"hmbirdcore_debug"        = 0
"iso_free_rescue"         = 0
"isoctrl_high_ratio"      = 75
"isoctrl_low_ratio"       = 60
"isolate_ctrl"            = 0
"misfit_ds"               = 90
"parctrl_high_ratio"      = 55
"parctrl_high_ratio_l"    = 65
"parctrl_low_ratio"       = 40
"parctrl_low_ratio_l"     = 50
"partial_ctrl"            = 1
"save_gov"                = 0
"scx_shadow_tick_enable"  = 1
"slim_for_app"            = 0
"slim_stats"              = 0
"watchdog_enable"         = 0
