# 写需要强开scx的游戏
[[hmbird_config]]
packages = [
    "com.miHoYo.Yuanshen",
    "com.miHoYo.GenshinImpact",
    "com.miHoYo.ys.bilibili",
    "com.miHoYo.yuanshencb",
    "com.miHoYo.hkrpg",
    "com.miHoYo.hkrpg.bilibili",
    "com.HoYoverse.hkrpgoversea",
    "com.miHoYo.hkrpgcb",
    "com.miHoYo.Nap",
    "com.tencent.KiHan",
    "com.ChillyRoom.DungeonShooter",
]

[[hmbird_config.node_value]]
key = "cluster_separate"
value = 0

[[hmbird_config.node_value]]
key = "cluster_separate"
value = 0

[[hmbird_config.node_value]]
key = "cpu7_tl"
value = 70

[[hmbird_config.node_value]]
key = "cpu_cluster_masks"
value = 3145728

[[hmbird_config.node_value]]
key = "cpuctrl_high"
value = 55

[[hmbird_config.node_value]]
key = "cpuctrl_low"
value = 40

[[hmbird_config.node_value]]
key = "highres_tick_ctrl_dbg"
value = 0

[[hmbird_config.node_value]]
key = "hmbird_preempt_policy"
value = 0

[[hmbird_config.node_value]]
key = "hmbirdcore_debug"
value = 0

[[hmbird_config.node_value]]
key = "iso_free_rescue"
value = 0

[[hmbird_config.node_value]]
key = "isoctrl_high_ratio"
value = 75

[[hmbird_config.node_value]]
key = "isoctrl_low_ratio"
value = 60

[[hmbird_config.node_value]]
key = "isolate_ctrl"
value = 0

[[hmbird_config.node_value]]
key = "misfit_ds"
value = 90

[[hmbird_config.node_value]]
key = "parctrl_high_ratio"
value = 55

[[hmbird_config.node_value]]
key = "parctrl_high_ratio_l"
value = 65

[[hmbird_config.node_value]]
key = "parctrl_low_ratio"
value = 40

[[hmbird_config.node_value]]
key = "parctrl_low_ratio_l"
value = 50

[[hmbird_config.node_value]]
key = "partial_ctrl"
value = 1

[[hmbird_config.node_value]]
key = "save_gov"
value = 0

[[hmbird_config.node_value]]
key = "scx_shadow_tick_enable"
value = 1

[[hmbird_config.node_value]]
key = "slim_for_app"
value = 0

[[hmbird_config.node_value]]
key = "slim_stats"
value = 0

[[hmbird_config.node_value]]
key = "watchdog_enable"
value = 0

[[hmbird_config]]
packages = [
    "com.hypergryph.arknights",
    "com.tencent.tmgp.pubgmhd",
    "com.tencent.tmgp.sgame",
]

[[hmbird_config.node_value]]
key = "cluster_separate"
value = 0

[[hmbird_config.node_value]]
key = "cpu7_tl"
value = 70

[[hmbird_config.node_value]]
key = "cpu_cluster_masks"
value = 524288160

[[hmbird_config.node_value]]
key = "cpuctrl_high"
value = 55

[[hmbird_config.node_value]]
key = "cpuctrl_low"
value = 40

[[hmbird_config.node_value]]
key = "highres_tick_ctrl_dbg"
value = 0

[[hmbird_config.node_value]]
key = "hmbird_preempt_policy"
value = 0

[[hmbird_config.node_value]]
key = "hmbirdcore_debug"
value = 0

[[hmbird_config.node_value]]
key = "iso_free_rescue"
value = 0

[[hmbird_config.node_value]]
key = "isoctrl_high_ratio"
value = 75

[[hmbird_config.node_value]]
key = "isoctrl_low_ratio"
value = 60

[[hmbird_config.node_value]]
key = "isolate_ctrl"
value = 0

[[hmbird_config.node_value]]
key = "misfit_ds"
value = 90

[[hmbird_config.node_value]]
key = "parctrl_high_ratio"
value = 55

[[hmbird_config.node_value]]
key = "parctrl_high_ratio_l"
value = 65

[[hmbird_config.node_value]]
key = "parctrl_low_ratio"
value = 40

[[hmbird_config.node_value]]
key = "parctrl_low_ratio_l"
value = 50

[[hmbird_config.node_value]]
key = "partial_ctrl"
value = 1

[[hmbird_config.node_value]]
key = "save_gov"
value = 0

[[hmbird_config.node_value]]
key = "scx_shadow_tick_enable"
value = 1

[[hmbird_config.node_value]]
key = "slim_for_app"
value = 0

[[hmbird_config.node_value]]
key = "slim_stats"
value = 0

[[hmbird_config.node_value]]
key = "watchdog_enable"
value = 0
